batch_size:
  gtype: ptwo
  min_power: 2
  max_power: 10

dropout:
  gtype: number
  precision: 3
  positive: yes
  avoid_zero: yes
  min_order: -3
  max_order: -3

optimizer:
  lr:
    gtype: number
    precision: 1
    positive: yes
    avoid_zero: yes
    min_order: -6
    max_order: -1

  momentum:
    gtype: number
    precision: 3
    positive: yes
    avoid_zero: yes
    min_order: -3
    max_order: -3

  nesterov:
    gtype: set
    domain: [True, False]

meta:
  crossover: .1
  random: .01
  selection: squared_rank

